@extends('layouts.master')
@section('content')
    <div class="main-container col-xs-12 col-sm-8 col-sm-offset-2">
        <div class="col-md-6 col-md-offset-3" style="font-size:1.2em">
            <br><br><br>
            <p> <span style="font-size:1.5em">I</span> distinctly recall laughing when Nyarlathotep announced himself to the world, declaring so matter-of-factly that he had risen from a sleep of 28 centuries to share truths from beyond this world, imparted by entities more ancient than the Universe itself. He spoke of science far beyond anything known and a truth deeper than imagined in any holy book. His obvious and unapologetic blasphemy in a land so torn by religious strife seemed to me, frankly, to be the most impossible part of his tale. Truly impossible that someone could survive, let alone find audience, within the backward villages of the country and the rural strongholds of the Muslim Brotherhood. Yet, women and men of every creed and station in life left his demonstrations and speeches changed. They emerged restless and full of a new conviction to abandon all which came before, sacred and secular. The weeks after his presence saw a new Sleepless Spring in fast forward as society fought the new ideas, then itself, then found the truth in his words within Tahrir Square. Never had peace come so suddenly to a people so torn by strife. Then again, never before had nightmares and insomnia been an epidemic public health crisis.</p>

            <p><span style="font-size:1.5em">I</span> remember when Nyarlathotep came to my city--a city of ingenuity-turned-rust, a city of broken promises, a city mirroring the greatness and failure of a people. A coworker told me of him and his incredible exhibition, of truth incomparable and unbelievable in the most literal sense, at least to those who had yet to see. She spoke of great and terrible sights and revelations that exceeded my most wild imagination, all brought by this man wearing the mystique of a bygone era and a name even more archaic, almost comically baroque. If a tenth the stories from the internet and the news were true, then this greatest of charlatains would be a show of a lifetime. Comedy of the absurd in its greatest form, told by a man that could speak any language and tear down the religions and old beliefs of the fools of any society.</p>

            <p><span style="font-size:1.5em">I</span>n the unseasonable heat, I gathered in the parking lot with the other ticket holders of my group. The usual party atmosphere of our group film nights unexpectedly absent. A nervous restlessness filled us. None who had seen him previously at other stops of his tour had taken the offer to join us, even when offered a free ticket, all declining in similar fashion. As we made our way into the arena, plodding up the steps to watch the show. The scene of hooded forms and ruined monuments projected onto the screen failed to impress until the scene itself began to pour through into the arena, a world burning in an enveloping darkness. Arcs of cold electricity burst forth, erupting from bodies of the attendance, striking into the portal and drawing out shadowy creatures that struck a primal fear in all of us. I, being the rational and critical type by nature, barked a half-hearted challenge of "light shows" and "crowd delirium," and it was then the lights shone with impossible brightness and Nyarlathotep himself commanded us from the arena. Driven out by a mutual desire to leave we made our way back down the stairs, flowing into the parking lots. I found myself defiantly shouting to the world that I was *not* afraid of these silly parlor tricks and woo woo fakery. It was not long before others were shouting defiance at what we had seen together, reassuring ourselves that the world was unchanged. As the parking lot lighting sputtered out, we mocked our cursed infrastruture and utilities, laughing at each other's one-upsmanship in doing so.</p>

            <p><span style="font-size:1.5em">I</span>t wasn't until I had passed the parking lot by several blocks that I realized we had all filed from the arena, flowing out into the streets with apparent destinations undiscussed but mutually agreed upon. The city around us, even the buildings marked by shining rebirth were now long abandoned derelicts of rusted metal and broken glass. The torn and overgrown streets marked the path for most. The flow of people split off regularly, twisting and turning through the city. A small group of people I once knew turned into an alley, leaving behind only pained groans. Another small pack pried open a manhole cover and laughter rose echoing from the hole as they leapt down one after another with a distressingly coordinated precision. My own group soon found itself wandering through the open plots of the buildings and homes long ago condemned, the paved-over collapse of a city with its truth laid bare in the freshly chill winds. The burning moon, flickering in colors of green and blue overhead, lit the way as the snows came and soon I found myself alone amongst the drifts, with only the dancing reflections of the crawling moon to keep me company.</p>

            <p><span style="font-size:1.5em">T</span>he shadows and figures did not hunt me, but I knew to fear them nonetheless. They were to me as I would have been to an insect. As had been promised, I knew. Their ancient forms had stalked this world and would do so again. Temples to the truth of existence buried in ruin, pointing to an unforgiving sky. The piping whines and writhing at the heart of this forgotten graveyard of a universe beckon to the timeless servants. Its center is home to a power undreamed of, a mindless form inconceivable and beyond time, beyond understanding. The pounding and rhythmless dance of the ancient will, mindless and blind, made form in the soul of Nyarlathotep.</p>
            <br><br><br>
        </div>
    </div>
@stop
